Added solution of crash at a public endpoint after an authenticated
MMquant/bfx-cpp-api pull request #4
Opened 2017-12-05 17:27 UTC by turing228

It crashes at request of a public endpoint after request of an authenticated endpoint.

Because of using the same curl during DoGETrequest and DoPOSTrequest, but the last injects trash (for DoGETrequest) into curl.

Here is a brilliant solution of this difficult for solving problem, so solution must be included at example.cpp because it's an example.

2017-12-08 20:42 UTC, turing228 commented
Now my solution doesn't mean using two diffirent cURL. If you note some disadvantages, please, don't be silent and just write here to let me know about it.

These pull requests make it possible for me to receive credit at the University :)

2017-12-10 09:45 UTC, MMquant commented on BitfinexAPI.cpp
> +		curl = curl_easy_init();
Fix indentation

2017-12-10 09:45 UTC, MMquant commented on BitfinexAPI.cpp
> +		curl = curl_easy_init();
Fix indentation

2017-12-10 09:47 UTC, MMquant requested changes
Fix indentation please so that I can squash and merge the patch.

2017-12-10 14:38 UTC, merged